let Level1;
/**
 * Initializes the game level with all the predefined objects.
 */
function initLevel() { 
    Level1 = new Level(
    [
        new Chicken(),
        new Chicken(),
        new Chicken(),
    ],
    [
        new Endboss(),
    ],
    [
        new Clouds(),
        new Clouds(),
        new Clouds(),
        new Clouds(),
        new Clouds(),
        new Clouds(),
        new Clouds(),
        new Clouds(),
        new Clouds(),
        new Clouds(),
        new Clouds(),
    ],
    [ 
        new BackgroundObject('img/img/5_background/layers/air.png', -719),
        new BackgroundObject('img/img/5_background/layers/3_third_layer/2.png', -719),
        new BackgroundObject('img/img/5_background/layers/2_second_layer/2.png', -719),
        new BackgroundObject('img/img/5_background/layers/1_first_layer/2.png', -719),
        new BackgroundObject('img/img/5_background/layers/air.png', 0),
        new BackgroundObject('img/img/5_background/layers/3_third_layer/1.png', 0),
        new BackgroundObject('img/img/5_background/layers/2_second_layer/1.png', 0),
        new BackgroundObject('img/img/5_background/layers/1_first_layer/1.png', 0),
        new BackgroundObject('img/img/5_background/layers/air.png', 719),
        new BackgroundObject('img/img/5_background/layers/3_third_layer/2.png', 719),
        new BackgroundObject('img/img/5_background/layers/2_second_layer/2.png', 719),
        new BackgroundObject('img/img/5_background/layers/1_first_layer/2.png', 719),
        new BackgroundObject('img/img/5_background/layers/air.png', 719 * 2),
        new BackgroundObject('img/img/5_background/layers/3_third_layer/1.png', 719 * 2),
        new BackgroundObject('img/img/5_background/layers/2_second_layer/1.png', 719 * 2),
        new BackgroundObject('img/img/5_background/layers/1_first_layer/1.png', 719 * 2),
        new BackgroundObject('img/img/5_background/layers/air.png', 719 * 3),
        new BackgroundObject('img/img/5_background/layers/3_third_layer/2.png', 719 * 3),
        new BackgroundObject('img/img/5_background/layers/2_second_layer/2.png', 719 * 3),
        new BackgroundObject('img/img/5_background/layers/1_first_layer/2.png', 719 * 3),
    ],
    [
        new Coin(),
        new Coin(),
        new Coin(),
        new Coin(),
        new Coin(),
        new Coin(),
        new Coin(),
        new Coin(),
        new Coin(),
        new Coin(),
      
    ],
    [
        new Bottle(),
        new Bottle(),
        new Bottle(),
        new Bottle(),
        new Bottle(),
        new Bottle(),
        new Bottle(),
        new Bottle(),
        new Bottle(),
        new Bottle(),
        new Bottle(),
        new Bottle(),
        new Bottle(),
        new Bottle(),
        new Bottle(),
        new Bottle(),
        new Bottle(),
    ],
    [
        new BabyChicken(),
        new BabyChicken(),
        new BabyChicken(),
        new BabyChicken(),
        new BabyChicken(),
    ],
);
}

